#!/bin/bash
function multiply_and_format { # expects a number and its multiplier. Returns the Number without the decimal point.
  local number=$1
  local multiplier=$2
  local result=$(echo "$number * $multiplier" | bc)
  local formatted_result=$(echo $result | sed 's/\.0*$//')
  echo $formatted_result
}

function get_current_mode {
# Return only the mode name without the passband
  echo $(rigctl -m 2 -r localhost:$port m | head -n 1)
}

