#!/bin/bash
is_within_input_range() {
  local index=$1
  local array=("${!2}")
  
  if (( index >= 0 && index < ${#array[@]} )); then
    return 1
  else
    return 0
  fi
}

my_array=("Element1" "Element2" "Element3" "Element4")
if is_within_input_range 2 my_array[@] && [ $? -eq 1 ]; then
  echo "passt"
else
  echo "passt nicht"
fi
