#!/bin/bash
is_within_input_range() {
  local index=$1
  local array=("${!2}")
  if (( index >= 0 && index < ${#array[@]} )); then
    return 0
  else
    return 1
  fi
}

# shellcheck disable=SC2034
my_array=("Element1" "Element2" "Element3" "Element4")
if is_within_input_range 22 my_array[@]; then
  echo "passt"
else
  echo "passt nicht"
fi
