#!/bin/bash

stdbuf -oL aseqdump -p $midi_device | while read line; do
  if [[ "$line" == *"Note"* ]]; then
    echo "note: $line"
    break
  elif [[ "$line" == *"Control change"* ]]; then
    echo "Control change: $line"
    break
  fi
done
