#!/bin/bash

stdbuf -oL aseqdump -p $midi_device | while read -r line; do
# Remove commas from the record
  line=$(echo $line | sed 's/,//g')
  if [[ $line == *"note"* || $line == *"Control change"* ]]; then
#   Extract data into variables
    type=$(echo $line | awk '{print $2}')
    channel=$(echo $line | awk '{print $4}')
    if [[ $type == "Control" ]]; then
      controller=$(echo $line | awk '{print $6}')
      value=$(echo $line | awk '{print $8}')
    fi
    if [[ $type == "Note" ]]; then
      on_off=$(echo $line | awk '{print $3}')
      note=$(echo $line | awk '{print $6}')
      velocity=$(echo $line | awk '{print $8}')
    fi
  fi
# Search MIDI map for the event definition
  if [[ $type == "Note" && $on_off == "on" ]]; then
    awk -v note=$note '$3 == note && $1 == "note_on" {print}' $midi_mapping_file
  fi
  if [[ $type == "Note" && $on_off == "off" ]]; then
    awk -v note=$note '$3 == note && $1 == "note_off" {print}' $midi_mapping_file
  fi
  if [[ $type == "Control" ]]; then
    awk -v controller=$controller '$3 == controller {print}' $midi_mapping_file
  fi
done
